apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart-app    # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80        # The port you'll use in the browser
      targetPort: 8080 # The port your Spring Boot app listens on
  type: LoadBalancer  # This tells Azure to create a Public IP



